# Site
name: 'Nut Based News'
description: 'Satire news site about veganism and animal liberation'
logo: 'assets/images/logo.png'
favicon: 'assets/images/favicon.ico'
baseurl: ''
disqus: 'nutbasednews'
email: 'nutbasednews@gmail.com'
mailchimp-list: 'https://nutbasednews.us14.list-manage.com/subscribe/post?u=30039bfac2449e3ca1444e5f5&amp;id=ae646eb9de'

include: ["_pages"]
permalink: /:title/

# Plugins
plugins: 
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-paginate
  - jekyll-seo-tag

authors:
    samuel:
      name:           Samuel
      site:           https://nutbasednews.com
      avatar:         assets/images/avatar1.jpg
      bio:            "Hi, I am Samuel, the creator of Nut Based News. I am a software engineer, but also write satirical articles related to veganism and animal rights in my spare time."
      email:          nutbasednews@gmail.com
      twitter:        https://twitter.com/nutbasednews

socials:
  twitter: https://twitter.com/nutbasednews
  instagram: https://instagram.com/nutbasednews

# Defaults
defaults:

  # all posts
  - scope:
      path: "_posts"
    values:
      layout: post
      author: samuel
      avatar: assets/images/avatar1.jpg
      
  # all pages
  - scope:
      path: "_pages"
    values:
      layout: page
      
# Syntax
markdown: kramdown
highlighter: rouge

# Paginate
paginate: 10



# Exclude metadata and development time dependencies (like Grunt plugins)
exclude: [README.markdown, package.json, grunt.js, Gruntfile.js, Gruntfile.coffee, node_modules]
